name: Build & Publish
on:
  push:
    branches:
      - development
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   name: Install Composer Dependencies
          run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      -   name: Install NPM Dependencies
          run: npm install --cache /tmp/empty-cache
      -   name: Build Site
          run: ./vendor/bin/jigsaw build production
      - name: Save cache
        run: |
          git add -f cache
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "update cache"
          git push -f
      -   name: Commit files
          if: success() || failure()
          run: |
            git add -f build_production
            git commit -m "Build for deploy"
      -   name: Publish
          run: |
            git subtree split --prefix build_production -b main
            git push -f origin main:main
            git branch -D main